version: "3.9"

x-app: &default-app
    image: spuder/gifr:latest
    volumes:
        - ./input:/input
        - ./output:/output

services:
    # taegeuk2-parts:
    #     <<: *default-app
    #     env_file:
    #         - sr-green/Taegeuk2Jang-Parts.env
    taegeuk2-complete:
        <<: *default-app
        env_file:
            - sr-green/Taegeuk2Jang-complete.env
    sr-green-form-complete:
        <<: *default-app
        env_file:
        - sr-green/SeniorGreenForm-complete.env
    sr-green-sparring:
        <<: *default-app
        env_file:
        - sr-green/SeniorGreenSparring.env
    sr-green-kicking:
        <<: *default-app
        env_file:
        - sr-green/SeniorGreenKicking.env
    sr-green-nunchuck:
        <<: *default-app
        env_file:
        - sr-green/SeniorGreenNunchuck.env