version: "3.9"

x-app: &default-app
    image: spuder/gifr:latest
    volumes:
        - ./input:/input
        - ./output:/output

services:
    taegeuk4-parts:
        <<: *default-app
        env_file:
            - taegeuk/sr-blue//Taegeuk4Jang-Parts.env
    taegeuk4-complete:
        <<: *default-app
        env_file:
            - taegeuk/sr-blue//Taegeuk4Jang-complete.env
    taegeuk/sr-blue/-form-complete:
        <<: *default-app
        env_file:
        - taegeuk/sr-blue//SeniorBlueForm-complete.env
    taegeuk/sr-blue/-sparring:
        <<: *default-app
        env_file:
        - taegeuk/sr-blue//SeniorBlueSparring.env