version: "3.9"

x-app: &default-app
    image: spuder/gifr:latest
    volumes:
        - ./input:/input
        - ./output:/output

services:
    # taegeuk3-parts:
    #     <<: *default-app
    #     env_file:
    #         - taegeuk/jr-blue/taegeuk3Jang-Parts.env
    taegeuk3-complete-640:
        <<: *default-app
        environment:
            - VIDEO_URL=https://www.youtube.com/watch?v=ksSqKt0UkWo
            - SPLITS=1:17^1:54
            - INPUT_FILE=Taegeuk3Jang.mp4
            - OUTPUT_FILE=Taegeuk3Jang
            - RESOLUTION=640
            - FPS=10
    taegeuk3-complete-480:
        <<: *default-app
        environment:
            - VIDEO_URL=https://www.youtube.com/watch?v=ksSqKt0UkWo
            - SPLITS=1:17^1:54
            - INPUT_FILE=Taegeuk3Jang.mp4
            - OUTPUT_FILE=Taegeuk3Jang
            - RESOLUTION=480
            - FPS=4
    jr-blue-form-complete-640:
        <<: *default-app
        environment:
            - VIDEO_URL=https://youtu.be/MDAcFJpAfgk
            - SPLITS=0:08^0:54
            - INPUT_FILE=Jr. Blue Belt Form.mp4
            - OUTPUT_FILE=JuniorBlueForm
            - RESOLUTION=640
            - FPS=10
    jr-blue-form-complete-480:
        <<: *default-app
        environment:
            - VIDEO_URL=https://youtu.be/MDAcFJpAfgk
            - SPLITS=0:08^0:54
            - INPUT_FILE=Jr. Blue Belt Form.mp4
            - OUTPUT_FILE=JuniorBlueForm
            - RESOLUTION=480
            - FPS=4
    jr-blue-sparring-640:
        <<: *default-app
        environment:
            # https://onedrive.live.com/?authkey=%21AA8GRPw%5F1nH9jFQ&cid=F8E1EC016F4B21B9&id=F8E1EC016F4B21B9%215435&parId=F8E1EC016F4B21B9%21478&o=OneUp
            - VIDEO_URL=https://youtu.be/EagcJ9zT_7w
            - SPLITS=12^19,25^32
            - INPUT_FILE=Jr. Blue Belt One Step Sparring.mp4
            - OUTPUT_FILE=JuniorBlueSparring
            - RESOLUTION=640
            - FPS=10
    jr-blue-sparring-480:
        <<: *default-app
        environment:
            # https://onedrive.live.com/?authkey=%21AA8GRPw%5F1nH9jFQ&cid=F8E1EC016F4B21B9&id=F8E1EC016F4B21B9%215435&parId=F8E1EC016F4B21B9%21478&o=OneUp
            - VIDEO_URL=https://youtu.be/EagcJ9zT_7w
            - SPLITS=12^19,25^32
            - INPUT_FILE=Jr. Blue Belt One Step Sparring.mp4
            - OUTPUT_FILE=JuniorBlueSparring
            - RESOLUTION=480
            - FPS=4
    jr-blue-kicking-640:
        <<: *default-app
        environment:
            # https://onedrive.live.com/?authkey=%21ACMyOBG4bkRsiRw&cid=F8E1EC016F4B21B9&id=F8E1EC016F4B21B9%215434&parId=F8E1EC016F4B21B9%21478&o=OneUp
            - VIDEO_URL=https://youtu.be/VMBV0-PW3pg
            - SPLITS=5^11,13^20
            - INPUT_FILE=Jr. Blue Belt Kicking.mp4
            - OUTPUT_FILE=JuniorBlueKicking
            - RESOLUTION=640
            - FPS=10
    jr-blue-kicking-480:
        <<: *default-app
        environment:
            # https://onedrive.live.com/?authkey=%21ACMyOBG4bkRsiRw&cid=F8E1EC016F4B21B9&id=F8E1EC016F4B21B9%215434&parId=F8E1EC016F4B21B9%21478&o=OneUp
            - VIDEO_URL=https://youtu.be/VMBV0-PW3pg
            - SPLITS=5^11,13^20
            - INPUT_FILE=Jr. Blue Belt Kicking.mp4
            - OUTPUT_FILE=JuniorBlueKicking
            - RESOLUTION=480
            - FPS=4
    jr-blue-nunchuck-640:
        <<: *default-app
        environment:
            - VIDEO_URL=https://youtu.be/B9k6Re_s_n8
            - SPLITS=6^45
            - INPUT_FILE=Jr. Blue Nunchukas.mp4
            - OUTPUT_FILE=JuniorBlueNunchuck
            - RESOLUTION=640
            - FPS=10
    jr-blue-nunchuck-480:
        <<: *default-app
        environment:
            - VIDEO_URL=https://youtu.be/B9k6Re_s_n8
            - SPLITS=6^45
            - INPUT_FILE=Jr. Blue Nunchukas.mp4
            - OUTPUT_FILE=JuniorBlueNunchuck
            - RESOLUTION=480
            - FPS=4