version: "3.9"

x-app: &default-app
    image: gifr
    volumes:
        - ./input:/input
        - ./output:/output

services:
    taegeuk3-parts:
        <<: *default-app
        env_file:
            - Taegeuk3Jang-Parts.env
    taegeuk3-complete:
        <<: *default-app
        env_file:
            - Taegeuk3Jang-complete.env
    # jr-blue-form-complete:
    #     <<: *default-app
    #     env_file:
    #     - JuniorBlueForm-complete.env
    jr-blue-sparring:
        <<: *default-app
        env_file:
        - JuniorBlueSparring.env
    jr-blue-kicking:
        <<: *default-app
        env_file:
        - JuniorBlueKicking.env