version: "3.9"

x-app: &default-app
    image: spuder/gifr:latest
    volumes:
        - ./input:/input
        - ./output:/output

services:
    # taegeuk1-parts:
    #     <<: *default-app
    #     env_file:
    #         - taegeuk/jr-green/Taegeuk1Jang-Parts.env
    taegeuk1-complete:
        <<: *default-app
        env_file:
            - taegeuk/jr-green/Taegeuk1Jang-complete.env
    jr-green-form-complete:
        <<: *default-app
        env_file:
        - taegeuk/jr-green/JuniorGreenForm-complete.env
    jr-green-sparring:
        <<: *default-app
        env_file:
        - taegeuk/jr-green/JuniorGreenSparring.env
    jr-green-kicking:
        <<: *default-app
        env_file:
        - taegeuk/jr-green/JuniorGreenKicking.env
    jr-green-nunchuck:
        <<: *default-app
        env_file:
        - taegeuk/jr-green/JuniorGreenNunchuck.env