version: "3.9"

x-app: &default-app
    image: spuder/gifr:latest
    volumes:
        - ./input:/input
        - ./output:/output

services:
    # taegeuk2-parts:
    #     <<: *default-app
    #     env_file:
    #         - taegeuk/sr-green//Taegeuk2Jang-Parts.env
    taegeuk2-complete:
        <<: *default-app
        env_file:
            - taegeuk/sr-green//Taegeuk2Jang-complete.env
    taegeuk/sr-green/-form-complete:
        <<: *default-app
        env_file:
        - taegeuk/sr-green//SeniorGreenForm-complete.env
    taegeuk/sr-green/-sparring:
        <<: *default-app
        env_file:
        - taegeuk/sr-green//SeniorGreenSparring.env
    taegeuk/sr-green/-kicking:
        <<: *default-app
        env_file:
        - taegeuk/sr-green//SeniorGreenKicking.env
    taegeuk/sr-green/-nunchuck:
        <<: *default-app
        env_file:
        - taegeuk/sr-green//SeniorGreenNunchuck.env