version: "3.9"

x-app: &default-app
    image: spuder/gifr:latest
    volumes:
        - ./input:/input
        - ./output:/output

services:
    taegeuk8-complete:
        <<: *default-app
        env_file:
            - taegeuk/sr-red//Taegeuk8Jang-complete.env
    taegeuk8-parts:
        <<: *default-app
        env_file:
            - taegeuk/sr-red//Taegeuk8Jang-parts.env
    taegeuk/sr-red/-form-complete:
        <<: *default-app
        env_file:
        - taegeuk/sr-red//SeniorRedForm-complete.env
    taegeuk/sr-red/-sparring:
        <<: *default-app
        env_file:
        - taegeuk/sr-red//SeniorRedSparring.env
    taegeuk/sr-red/-kicking:
        <<: *default-app
        env_file:
        - taegeuk/sr-red//SeniorRedKicking.env
    taegeuk/sr-red/-nunchuck:
        <<: *default-app
        env_file:
        - taegeuk/sr-red//SeniorRedNunchuckas.env